//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.UseTheService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mysite.com/", ConfigurationName="UseTheService.TheServiceSoap")]
    public interface TheServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysite.com/DoAdd", ReplyAction="*")]
        int DoAdd(int Value1, int Value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysite.com/DoAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DoAddAsync(int Value1, int Value2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TheServiceSoapChannel : TestApp.UseTheService.TheServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TheServiceSoapClient : System.ServiceModel.ClientBase<TestApp.UseTheService.TheServiceSoap>, TestApp.UseTheService.TheServiceSoap {
        
        public TheServiceSoapClient() {
        }
        
        public TheServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TheServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoAdd(int Value1, int Value2) {
            return base.Channel.DoAdd(Value1, Value2);
        }
        
        public System.Threading.Tasks.Task<int> DoAddAsync(int Value1, int Value2) {
            return base.Channel.DoAddAsync(Value1, Value2);
        }
    }
}
